feature_engineering : 
    - LogDebtRatio : {
      feature_source : DebtRatio
      description : |
              The form log np.log1p(DebtRatio)
    }
    - log_RevolvingUtilizationOfUnsecuredLines : {
      feature_source : RevolvingUtilizationOfUnsecuredLines
      description : |
              The form log np.log1p(RevolvingUtilizationOfUnsecuredLines)
    }
    - log_RevolvingUtilizationOfUnsecuredLines : {
      feature_source : RevolvingUtilizationOfUnsecuredLines
      description : |
              The form log 
              np.log1p(RevolvingUtilizationOfUnsecuredLines)
    }
    - bin_income : {
      feature_source : MonhtlyIncome
      description : |
              The form discretization of MonhtlyIncome 
              based on quqrtile 0,q1,q2,q3 based on training data 
    }

preprocessing_step : 
    - NumberOfDependents : {
    feature_source : NumberOfDependents
    description : |
            Filling Missing Values based on median value on training data 
  }
    - MonthlyIncome : {
    feature_source : MonthlyIncome
    description : |
            Filling Missing Values based on median value on training data 
  }

